audit_header: false
title: Louisiana Real Estate Video Blog with Jason Delatte
description: Our mission at Delatte Group is to be your best resource for Louisiana real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Delatte Group, your professional Louisiana Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Jason Delatte
  title:
  license_number:
  about_markdown: |
    Our philosophy is simple: clients come first. We pledge to be in constant communication with our clients, keeping them fully informed throughout the entire buying or selling process. We believe that if you’re not left with an amazing experience, we haven’t done our job. We don’t measure success through achievements or awards, but through the satisfaction of our clients.
  market: Louisiana
  brand: Delatte Group
  brokerage: Keller Williams Realty Bayou Partners
  address: 307 Bayou Gardens Blvd<br>Houma, LA 70364
  phone: 985-859-3375
  phone_type: Cell
  phone2: 985-262-4400
  phone2_type: Office
  email: jasondelatte@kw.com
  url: http://JasonDelatte.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.jasondelatte.com/your-home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.jasondelatte.com/listings-search/#/398466887

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your Louisiana Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.jasondelatte.com/your-home-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a Louisiana Home?"
    CTA_text2: "Search the entire MLS for your Louisiana home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.jasondelatte.com/listings-search/#/398466887

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/thedelattedifference/
  linkedin_url: https://www.linkedin.com/in/jason-delatte-realtor-b68502103/
  gplus_url: https://plus.google.com/b/104389134788092725959
  youtube_url: https://www.youtube.com/channel/UCU-ArBNUn3VqLI23ZdwMaUQ
  twitter_url: https://twitter.com/JasonDelatte
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/jasondelatte/
  trulia_url: https://www.trulia.com/profile/jason-delatte-agent-houma-la-zg9lw8zq/overview
  yelp_url: https://www.yelp.com/biz/keller-williams-realty-bayou-partners-houma
  podcast_url: https://itunes.apple.com/us/podcast/jason-delatte-with-keller-williams-realty-bayou-partners/id1242992203?mt=2

podcast:
  title: 'Louisiana Real Estate Podcast with Jason Delatte'
  categories: Education
  image: /img/podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Louisiana Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Delatte Group - your professional Louisiana Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Louisiana, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jason Delatte'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: Louisiana Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#c8202f'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
